                                24/08/2026

Numpy is a Python Library , was created in 2005 by Travis Oliphant. Numpy is used for working with arrays. Numpy is short for "Numerical Python". 50x faster than traditional python lists

In [ ]:
# importing numpy library
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


# different way to create numpy array


In [ ]:
# to create an ndarray ,we can pass a list , tuple or
# other array like object

In [ ]:
#create 2D array
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
# to see the dimension
print(arr3.ndim)
print(arr1.ndim)

2
1


In [ ]:
# create 3d array
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr4)
print(arr4.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
2


In [ ]:
# numpy Array indexing
arr5=np.array([1,2,3,4,5])
print(arr5[2])

3


In [ ]:
print(arr5[0:3])
# using Negative index

print(arr5[-1])
print(arr5[-2:-1])

[1 2 3]
5
[4]


In [ ]:
# get third and fourth elements from the following array and add them
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
# Access the elemnt of first row , second column
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ',arr[0,1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [ ]:
# Access the element on the 2nd row,5th column
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ',arr[1,4])

5th element on 2nd row:  10


In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 1 11 12]]]
6


In [ ]:
# Negative Indexing
# Print the last element from the 2nd dim
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ',arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [ ]:
# Slice elements from index 1 to index 5 from the following array:
import numpy as np
arr = np.array([10,20,30,40,50,60,75])
print(arr[1:5])

# Slice elements from index 4 to the end of the array
print(arr[4:])

# Slice elements from the beginning to index 4 (not included)
print(arr[:4])

[20 30 40 50]


In [ ]:
# Negative slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[-3:-1])


[1 2 3 4 5 6 7]
[5 6]


In [ ]:
# Passing step
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

# return every other element from the entire array
print(arr[::2])

[2 4]
[1 3 5 7]


In [ ]:
# Slicing 2D Arrays
# from the second element, slice elements from index 1 to index 4(not incuded)

import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])


[7 8 9]


In [ ]:
# from the arrays , slice elements from index 1 to index 4(not included)
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Data Types in Numpy

Numpy has some extra data types and refer to data types with one character like i for integers , u for unsigned integers etc.


In [ ]:
# Get the data type of an array object
import numpy as np
arr= np.array([1,2,3])
print(arr.dtype)

int64


In [ ]:
# creating array with the define data types
import numpy as np

arr= np.array([1,2,3,4],dtype='S')
arr1= np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)
print(arr1.dtype)

[b'1' b'2' b'3' b'4']
|S1
int32


In [ ]:
# change data type from float to integer by using 'i' as parameter value:
import numpy as np
arr= np.array([1.1,2.1,3.1])
newarr =arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Numpy array Copy Vs View

The main difference between a copy and a view of an array is that copy is a new array and the view is just a view of the original array

In [ ]:
# Make a copy change the original array anddisplay both array

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)

[42  2  3  4  5]


In [ ]:
# view

import numpy as np
arr = np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# Numpy array shape

import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
# Numpy Array reshaping

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Flattening the array

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
